//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recrutment_system.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANDIDATE_POSITION
    {
        public int CandidateId { get; set; }
        public int CompanyId { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public int HrId { get; set; }
        public string CandidateCode { get; set; }
        public string CandidateEmail { get; set; }
        public double Candidate_Yof_exp { get; set; }
        public Nullable<bool> ISActive { get; set; }
    }
}
