//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recrutment_system.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_HR_REGISTER
    {
        public int HrId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string HrName { get; set; }
        public string HrContact { get; set; }
        public string HrEmail { get; set; }
    
        public virtual COMPANY_REGISTER COMPANY_REGISTER { get; set; }
    }
}
