//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recrutment_system.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_REGISTER_REFRENCES
    {
        public int ComapanyRefId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string CompanyEmailRef { get; set; }
        public string CompanyPassword { get; set; }
        public string CompanyType { get; set; }
        public Nullable<bool> ConfirmedEmail { get; set; }
    
        public virtual COMPANY_REGISTER COMPANY_REGISTER { get; set; }
    }
}
