//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recrutment_system.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_JOB_OPENING
    {
        public int DepatmentID { get; set; }
        public int CompanyId { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public string RequestedBy { get; set; }
        public int HrId { get; set; }
        public string HrEmail { get; set; }
        public string Name_of_Vacancy { get; set; }
        public decimal Number_of_Position { get; set; }
        public string Required_Technical_Skill { get; set; }
        public string Special_Technical_Skill { get; set; }
        public double Min_Yearof_Experience { get; set; }
        public string Min_Qualification { get; set; }
        public Nullable<System.DateTime> Deadline_Date { get; set; }
        public Nullable<System.DateTime> Requested_Date { get; set; }
        public Nullable<bool> Approval { get; set; }
    }
}
