//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recrutment_system.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_JOB_OPENING_REFRENCES
    {
        public int Job_refrenceId { get; set; }
        public int CompanyId { get; set; }
        public string DepartmentCode { get; set; }
        public int HrId { get; set; }
        public Nullable<decimal> Number_of_Position { get; set; }
        public Nullable<System.DateTime> RowcreatedDate { get; set; }
        public Nullable<System.DateTime> RowModifiddate { get; set; }
    }
}
