//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recrutment_system.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Round_Detail_feedback
    {
        public int RoundId { get; set; }
        public int CompanyId { get; set; }
        public string CandidateCode { get; set; }
        public string DepartmentCode { get; set; }
        public int HrId { get; set; }
        public string RoundOne { get; set; }
        public Nullable<int> RoundOne_per { get; set; }
        public string RoundTwo { get; set; }
        public Nullable<int> RoundTwo_per { get; set; }
        public string RoundThree { get; set; }
        public Nullable<int> RoundThree_per { get; set; }
        public Nullable<int> totalround_per { get; set; }
    }
}
